name: dreamflow
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  url_launcher: ^6.0.0
  csv: ^6.0.0
  image_picker: '>=1.1.2'
  sign_in_with_apple: '>=6.1.2'
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  firebase_core: '>=2.21.1'
  firebase_storage: '>=12.3.4'
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  staggered_grid_view_flutter: ^0.0.4
  share_plus: ^7.0.0
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0
  pdf: ^3.10.0
  youtube_player_flutter: ^9.0.3
  just_audio: ^0.9.40
  audio_video_progress_bar: ^2.0.3
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_jt.png
