import 'package:flutter/material.dart';
import '../../../theme.dart';

/// Classe contenant les thèmes prédéfinis avec leurs passages bibliques
class PredefinedThemes {
  static List<Map<String, dynamic>> getDefaultThemes() {
    return [
      {
        'name': 'Amour',
        'description': 'Versets sur l\'amour de Dieu et l\'amour fraternel',
        'color': Colors.pink.value,
        'iconCodePoint': Icons.favorite.codePoint,
        'iconFontFamily': Icons.favorite.fontFamily,
        'passages': [
          {
            'reference': 'Jean 3:16',
            'book': 'Jean',
            'chapter': 3,
            'startVerse': 16,
            'description': 'L\'amour suprême de Dieu pour l\'humanité',
          },
          {
            'reference': '1 Corinthiens 13:4-7',
            'book': '1 Corinthiens',
            'chapter': 13,
            'startVerse': 4,
            'endVerse': 7,
            'description': 'La définition divine de l\'amour',
          },
          {
            'reference': '1 Jean 4:8',
            'book': '1 Jean',
            'chapter': 4,
            'startVerse': 8,
            'description': 'Dieu est amour',
          },
          {
            'reference': 'Romains 8:38-39',
            'book': 'Romains',
            'chapter': 8,
            'startVerse': 38,
            'endVerse': 39,
            'description': 'Rien ne peut nous séparer de l\'amour de Dieu',
          },
          {
            'reference': 'Matthieu 22:37-39',
            'book': 'Matthieu',
            'chapter': 22,
            'startVerse': 37,
            'endVerse': 39,
            'description': 'Le plus grand commandement',
          },
          {
            'reference': '1 Jean 4:19',
            'book': '1 Jean',
            'chapter': 4,
            'startVerse': 19,
            'description': 'Nous l\'aimons, parce qu\'il nous a aimés le premier',
          },
        ],
      },
      {
        'name': 'Espoir',
        'description': 'Messages d\'espérance et de confiance en Dieu',
        'color': Theme.of(context).colorScheme.successColor.value,
        'iconCodePoint': Icons.brightness_high.codePoint,
        'iconFontFamily': Icons.brightness_high.fontFamily,
        'passages': [
          {
            'reference': 'Jérémie 29:11',
            'book': 'Jérémie',
            'chapter': 29,
            'startVerse': 11,
            'description': 'Les projets de paix de Dieu pour nous',
          },
          {
            'reference': 'Romains 8:28',
            'book': 'Romains',
            'chapter': 8,
            'startVerse': 28,
            'description': 'Toutes choses concourent au bien',
          },
          {
            'reference': 'Hébreux 11:1',
            'book': 'Hébreux',
            'chapter': 11,
            'startVerse': 1,
            'description': 'La définition de la foi',
          },
          {
            'reference': 'Lamentations 3:22-23',
            'book': 'Lamentations',
            'chapter': 3,
            'startVerse': 22,
            'endVerse': 23,
            'description': 'Les compassions de Dieu se renouvellent',
          },
          {
            'reference': 'Psaume 27:14',
            'book': 'Psaumes',
            'chapter': 27,
            'startVerse': 14,
            'description': 'Attendre l\'Éternel avec courage',
          },
          {
            'reference': 'Ésaïe 40:29',
            'book': 'Ésaïe',
            'chapter': 40,
            'startVerse': 29,
            'description': 'Il donne de la force à celui qui est fatigué',
          },
        ],
      },
      {
        'name': 'Paix',
        'description': 'Versets sur la paix intérieure et la réconciliation',
        'color': Colors.blue.value,
        'iconCodePoint': Icons.spa.codePoint,
        'iconFontFamily': Icons.spa.fontFamily,
        'passages': [
          {
            'reference': 'Philippiens 4:6-7',
            'book': 'Philippiens',
            'chapter': 4,
            'startVerse': 6,
            'endVerse': 7,
            'description': 'La paix qui surpasse toute intelligence',
          },
          {
            'reference': 'Jean 14:27',
            'book': 'Jean',
            'chapter': 14,
            'startVerse': 27,
            'description': 'Je vous laisse la paix',
          },
          {
            'reference': 'Ésaïe 26:3',
            'book': 'Ésaïe',
            'chapter': 26,
            'startVerse': 3,
            'description': 'Une paix parfaite pour celui qui se confie',
          },
          {
            'reference': 'Colossiens 3:15',
            'book': 'Colossiens',
            'chapter': 3,
            'startVerse': 15,
            'description': 'Que la paix de Christ règne dans vos cœurs',
          },
          {
            'reference': 'Matthieu 5:9',
            'book': 'Matthieu',
            'chapter': 5,
            'startVerse': 9,
            'description': 'Heureux ceux qui procurent la paix',
          },
          {
            'reference': 'Jean 16:33',
            'book': 'Jean',
            'chapter': 16,
            'startVerse': 33,
            'description': 'Prenez courage ! J\'ai vaincu le monde',
          },
        ],
      },
      {
        'name': 'Sagesse',
        'description': 'Enseignements sur la sagesse divine et la connaissance',
        'color': Theme.of(context).colorScheme.warningColor.value,
        'iconCodePoint': Icons.lightbulb.codePoint,
        'iconFontFamily': Icons.lightbulb.fontFamily,
        'passages': [
          {
            'reference': 'Proverbes 9:10',
            'book': 'Proverbes',
            'chapter': 9,
            'startVerse': 10,
            'description': 'Le commencement de la sagesse',
          },
          {
            'reference': 'Jacques 1:5',
            'book': 'Jacques',
            'chapter': 1,
            'startVerse': 5,
            'description': 'Demander la sagesse à Dieu',
          },
          {
            'reference': 'Proverbes 3:5-6',
            'book': 'Proverbes',
            'chapter': 3,
            'startVerse': 5,
            'endVerse': 6,
            'description': 'Se confier en l\'Éternel de tout son cœur',
          },
          {
            'reference': '1 Corinthiens 1:25',
            'book': '1 Corinthiens',
            'chapter': 1,
            'startVerse': 25,
            'description': 'La folie de Dieu est plus sage que les hommes',
          },
          {
            'reference': 'Ecclésiaste 3:1',
            'book': 'Ecclésiaste',
            'chapter': 3,
            'startVerse': 1,
            'description': 'Il y a un temps pour toute chose',
          },
          {
            'reference': 'Proverbes 27:17',
            'book': 'Proverbes',
            'chapter': 27,
            'startVerse': 17,
            'description': 'Le fer aiguise le fer',
          },
        ],
      },
      {
        'name': 'Force',
        'description': 'Sources de force et de courage dans l\'adversité',
        'color': Colors.purple.value,
        'iconCodePoint': Icons.security.codePoint,
        'iconFontFamily': Icons.security.fontFamily,
        'passages': [
          {
            'reference': 'Philippiens 4:13',
            'book': 'Philippiens',
            'chapter': 4,
            'startVerse': 13,
            'description': 'Je puis tout par celui qui me fortifie',
          },
          {
            'reference': 'Ésaïe 40:31',
            'book': 'Ésaïe',
            'chapter': 40,
            'startVerse': 31,
            'description': 'Ceux qui se confient en l\'Éternel reprennent force',
          },
          {
            'reference': '2 Corinthiens 12:9',
            'book': '2 Corinthiens',
            'chapter': 12,
            'startVerse': 9,
            'description': 'Ma grâce te suffit',
          },
          {
            'reference': 'Josué 1:9',
            'book': 'Josué',
            'chapter': 1,
            'startVerse': 9,
            'description': 'Fortifie-toi et prends courage',
          },
          {
            'reference': 'Psaume 46:2',
            'book': 'Psaumes',
            'chapter': 46,
            'startVerse': 2,
            'description': 'Dieu est notre refuge et notre force',
          },
          {
            'reference': '1 Corinthiens 16:13',
            'book': '1 Corinthiens',
            'chapter': 16,
            'startVerse': 13,
            'description': 'Veillez, demeurez fermes dans la foi',
          },
        ],
      },
      {
        'name': 'Pardon',
        'description': 'Versets sur le pardon divin et la miséricorde',
        'color': Colors.teal.value,
        'iconCodePoint': Icons.handshake.codePoint,
        'iconFontFamily': Icons.handshake.fontFamily,
        'passages': [
          {
            'reference': '1 Jean 1:9',
            'book': '1 Jean',
            'chapter': 1,
            'startVerse': 9,
            'description': 'Il est fidèle et juste pour nous pardonner',
          },
          {
            'reference': 'Éphésiens 4:32',
            'book': 'Éphésiens',
            'chapter': 4,
            'startVerse': 32,
            'description': 'Soyez bons les uns envers les autres',
          },
          {
            'reference': 'Matthieu 6:14-15',
            'book': 'Matthieu',
            'chapter': 6,
            'startVerse': 14,
            'endVerse': 15,
            'description': 'Si vous pardonnez aux hommes',
          },
          {
            'reference': 'Psaume 103:12',
            'book': 'Psaumes',
            'chapter': 103,
            'startVerse': 12,
            'description': 'Autant l\'orient est éloigné de l\'occident',
          },
          {
            'reference': 'Colossiens 3:13',
            'book': 'Colossiens',
            'chapter': 3,
            'startVerse': 13,
            'description': 'Comme Christ vous a pardonné',
          },
          {
            'reference': 'Luc 23:34',
            'book': 'Luc',
            'chapter': 23,
            'startVerse': 34,
            'description': 'Père, pardonne-leur',
          },
        ],
      },
      {
        'name': 'Foi',
        'description': 'Versets sur la foi et la confiance en Dieu',
        'color': Colors.indigo.value,
        'iconCodePoint': Icons.star.codePoint,
        'iconFontFamily': Icons.star.fontFamily,
        'passages': [
          {
            'reference': 'Hébreux 11:6',
            'book': 'Hébreux',
            'chapter': 11,
            'startVerse': 6,
            'description': 'Sans la foi, il est impossible de plaire à Dieu',
          },
          {
            'reference': 'Marc 11:24',
            'book': 'Marc',
            'chapter': 11,
            'startVerse': 24,
            'description': 'Tout ce que vous demanderez en priant',
          },
          {
            'reference': 'Romains 10:17',
            'book': 'Romains',
            'chapter': 10,
            'startVerse': 17,
            'description': 'La foi vient de ce qu\'on entend',
          },
          {
            'reference': 'Matthieu 17:20',
            'book': 'Matthieu',
            'chapter': 17,
            'startVerse': 20,
            'description': 'Si vous aviez de la foi comme un grain de sénevé',
          },
          {
            'reference': '2 Corinthiens 5:7',
            'book': '2 Corinthiens',
            'chapter': 5,
            'startVerse': 7,
            'description': 'Nous marchons par la foi et non par la vue',
          },
          {
            'reference': 'Romains 1:17',
            'book': 'Romains',
            'chapter': 1,
            'startVerse': 17,
            'description': 'Le juste vivra par la foi',
          },
        ],
      },
      {
        'name': 'Gratitude',
        'description': 'Versets sur la reconnaissance et les actions de grâces',
        'color': Colors.amber.value,
        'iconCodePoint': Icons.celebration.codePoint,
        'iconFontFamily': Icons.celebration.fontFamily,
        'passages': [
          {
            'reference': '1 Thessaloniciens 5:18',
            'book': '1 Thessaloniciens',
            'chapter': 5,
            'startVerse': 18,
            'description': 'Rendez grâces en toutes choses',
          },
          {
            'reference': 'Psaume 100:4',
            'book': 'Psaumes',
            'chapter': 100,
            'startVerse': 4,
            'description': 'Entrez dans ses portes avec des louanges',
          },
          {
            'reference': 'Colossiens 3:17',
            'book': 'Colossiens',
            'chapter': 3,
            'startVerse': 17,
            'description': 'Faites tout au nom du Seigneur Jésus',
          },
          {
            'reference': 'Éphésiens 5:20',
            'book': 'Éphésiens',
            'chapter': 5,
            'startVerse': 20,
            'description': 'Rendez continuellement grâces pour toutes choses',
          },
          {
            'reference': 'Psaume 107:1',
            'book': 'Psaumes',
            'chapter': 107,
            'startVerse': 1,
            'description': 'Louez l\'Éternel, car il est bon',
          },
          {
            'reference': 'Psaume 136:1',
            'book': 'Psaumes',
            'chapter': 136,
            'startVerse': 1,
            'description': 'Louez l\'Éternel, car sa miséricorde dure à toujours',
          },
        ],
      },
      {
        'name': 'Protection',
        'description': 'Versets sur la protection divine et la sécurité en Dieu',
        'color': Colors.deepPurple.value,
        'iconCodePoint': Icons.shield.codePoint,
        'iconFontFamily': Icons.shield.fontFamily,
        'passages': [
          {
            'reference': 'Psaume 91:1-2',
            'book': 'Psaumes',
            'chapter': 91,
            'startVerse': 1,
            'endVerse': 2,
            'description': 'Celui qui demeure sous l\'abri du Très-Haut',
          },
          {
            'reference': 'Psaume 23:1',
            'book': 'Psaumes',
            'chapter': 23,
            'startVerse': 1,
            'description': 'L\'Éternel est mon berger',
          },
          {
            'reference': 'Deutéronome 31:6',
            'book': 'Deutéronome',
            'chapter': 31,
            'startVerse': 6,
            'description': 'Il ne te délaissera point',
          },
          {
            'reference': 'Proverbes 18:10',
            'book': 'Proverbes',
            'chapter': 18,
            'startVerse': 10,
            'description': 'Le nom de l\'Éternel est une tour forte',
          },
          {
            'reference': 'Psaume 121:7-8',
            'book': 'Psaumes',
            'chapter': 121,
            'startVerse': 7,
            'endVerse': 8,
            'description': 'L\'Éternel te gardera de tout mal',
          },
        ],
      },
      {
        'name': 'Guidance',
        'description': 'Versets sur la direction divine et la volonté de Dieu',
        'color': Colors.cyan.value,
        'iconCodePoint': Icons.explore.codePoint,
        'iconFontFamily': Icons.explore.fontFamily,
        'passages': [
          {
            'reference': 'Psaume 32:8',
            'book': 'Psaumes',
            'chapter': 32,
            'startVerse': 8,
            'description': 'Je t\'instruirai et te montrerai la voie',
          },
          {
            'reference': 'Proverbes 16:9',
            'book': 'Proverbes',
            'chapter': 16,
            'startVerse': 9,
            'description': 'Le cœur de l\'homme médite sa voie',
          },
          {
            'reference': 'Jérémie 10:23',
            'book': 'Jérémie',
            'chapter': 10,
            'startVerse': 23,
            'description': 'Ce n\'est pas à l\'homme que marchent ses voies',
          },
          {
            'reference': 'Psaume 119:105',
            'book': 'Psaumes',
            'chapter': 119,
            'startVerse': 105,
            'description': 'Ta parole est une lampe à mes pieds',
          },
          {
            'reference': 'Jean 16:13',
            'book': 'Jean',
            'chapter': 16,
            'startVerse': 13,
            'description': 'L\'Esprit de vérité vous conduira',
          },
        ],
      },
    ];
  }
}
