// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXVvkNjuRnvP7Z3OwOjft_Ye9Qzndtc2I',
    appId: '1:270094003281:web:b2ae6c495e6b4e190c9c70',
    messagingSenderId: '270094003281',
    projectId: 'hjye25u8iwm0i0zls78urffsc0jcgj',
    authDomain: 'hjye25u8iwm0i0zls78urffsc0jcgj.firebaseapp.com',
    storageBucket: 'hjye25u8iwm0i0zls78urffsc0jcgj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACx0w-l-em_i3_oGgtof68P0PzD_Wlv9M',
    appId: '1:270094003281:ios:5f5d75ebbae8d3ea0c9c70',
    messagingSenderId: '270094003281',
    projectId: 'hjye25u8iwm0i0zls78urffsc0jcgj',
    storageBucket: 'hjye25u8iwm0i0zls78urffsc0jcgj.firebasestorage.app',
    iosBundleId: 'com.mycompany.Personnes',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt39b9hDnnGglA269igFpXpqtUDtBadwQ',
    appId: '1:270094003281:android:3d061912930c6fc50c9c70',
    messagingSenderId: '270094003281',
    projectId: 'hjye25u8iwm0i0zls78urffsc0jcgj',
    storageBucket: 'hjye25u8iwm0i0zls78urffsc0jcgj.firebasestorage.app',
  );

}